### PR TITLE
House keeping to pass Travis

### PR DESCRIPTION
**Pull request by koheiw**
Version number should be incremented to reflect the fix and to be consistent with NEWS.

### CODE REVIEW

**Comment by koheiw** [comment]
I did a few house keepingworks for you to make CI work. I believe that other PR will also pass Travis once you merge this.

**Comment by briatte** [comment]
Dear @koheiw 

First of all, all apologies for not answering this PR earlier.

Many thanks for your suggestions: I have reflected most of them in the current build, and they helped a lot with Travis CI indeed! I'll be adding you to the "thank you" notes of the README and NEWS files.

Also, your [`newsmap`](https://cran.r-project.org/package=newsmap) package (discovered via your blog) looks awesome, will certainly use it (I have large amounts of tweets and need to find those in French)!

**Comment by koheiw** [comment]
@briatte Great to see **ggplotnetwork** to be updated. **newsmap** has French dictionary by Claude Grasland, who is not really on Github, but please check for typo. PR is always welcome.

**Comment by briatte** [comment]
Will do1

**Pull request closed without merging**
